feature/user-data-endpoint
CodaTechS/backend-coda-tech pull request #1
Opened 2024-02-20 22:16 UTC by Igoreleven

Adds a new endpoint for the contact form, allowing users to submit their information and receive a confirmation of submission. This endpoint processes the form data and displays it in the server console, as well as sends a thank-you message to the user.

2024-02-20 22:42 UTC, LeoCosta001 requested changes

2024-02-20 22:42 UTC, LeoCosta001 commented on src/routes/contact/router.ts
> +});
O servidor já é ligado no arquivo `server/app.ts`, não precisa executar o método `.listen(...)` em outro lugar da aplicação.

```suggestion
```

2024-02-20 22:42 UTC, LeoCosta001 commented on src/routes/contact/router.ts
> +const port = 8080;
A posta do servidor é definida nos arquivos de ambiente, que ficam nos arquivos do diretório `environment/`.
OBS: Por padrão está na porta "3000", mas não precisa alterar elas... Caso essa porta já esteja em uso no seu computador é só alterar durante o desenvolvimento, mas não precisa incluir isto no commit.

```suggestion
```

2024-02-20 22:42 UTC, LeoCosta001 commented on src/routes/contact/router.ts
> +const app = express();
O express já é inicializado no arquivo `server/app.ts` não precisa criar uma nova instância.

OBS: Como estamos usando o JavaScript modules, então as importações são feitas com o `import` ao invés do `require`.

```suggestion
```

2024-02-20 22:42 UTC, LeoCosta001 commented on src/routes/contact/router.ts
>  });
Nesta aplicação não precisa retornar um formulário... A idéia a o front enviar uma requisição e só teriamos que lidar com os dados recebidos.

Se a ideia era usar para testes, então podemos usar ferramentas como o Postman ou Insominia para testar os endpoints, sem a necessidade de uma página web.
```suggestion
```

2024-02-20 22:42 UTC, LeoCosta001 commented on package.json
> +    "node.js": "^0.0.1-security",
Já temos o express como dependência do projeto, e o nodejs instalamos no nosso próprio ambiente de desenvolvimento (nosso PC) ao invés de usar como dependência direta do projeto.

```suggestion
```

2024-02-20 22:42 UTC, LeoCosta001 commented on package-lock.json
>        "dependencies": {
Após alterar o arquivo `package.json` é só rodar o comando `npm install` que ele atualizara este arquivo automaticamente`.

2024-02-20 22:42 UTC, LeoCosta001 commented on .vscode/launch.json
> +{
Este arquivo é usado em que?

2024-02-20 22:51 UTC, Igoreleven commented on src/routes/contact/router.ts
>  });
Sim, era apenas para teste!

2024-02-22 22:52 UTC, LeoCosta001 approved these changes, later dismissed

2024-02-23 02:14 UTC, Igoreleven commented on .vscode/launch.json
> +{
Apenas para conseguir abrir o local host no meu navegador

2024-02-23 02:14 UTC, Igoreleven commented on src/routes/contact/router.ts
> +const app = express();
Sem estas linhas o código não funciona, já testei

2024-02-23 02:14 UTC, Igoreleven commented on src/routes/contact/router.ts
> +const port = 8080;
ok, vou retirar

2024-02-23 02:14 UTC, Igoreleven commented on package.json
> +    "node.js": "^0.0.1-security",
ok, vou retirar

2024-02-23 02:17 UTC, Igoreleven reviewed
ok

2024-02-27 22:38 UTC, LeoCosta001 approved these changes

2024-02-27 22:38 UTC, merged